export interface Driver {
  id: string;
  number: number;
  name: string;
  firstName: string;
  lastName: string;
  shortName: string;
  teamId: string;
  nationality: string;
  flag: string;
  age: number;
  podiums: number;
  wins: number;
  poles: number;
  championships: number;
  points: number;
  position: number;
  fastestLaps: number;
  grandsPrix: number;
  bio: string;
  seasonPoints: number[];
  photo: string | null;
}

export interface Team {
  id: string;
  name: string;
  shortName: string;
  color: string;
  secondColor: string;
  drivers: string[];
  points: number;
  position: number;
  wins: number;
  podiums: number;
  poles: number;
  championships: number;
  base: string;
  powerUnit: string;
  firstEntry: number;
  bio: string;
  headerImage?: string;
}

export const TEAM_HEADER_IMAGES: Record<string, string> = {
  mclaren: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/mclaren.jpg",
  ferrari: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/ferrari.jpg",
  redbull: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/red-bull-racing.jpg",
  mercedes: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/mercedes.jpg",
  astonmartin: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/aston-martin.jpg",
  williams: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/williams.jpg",
  alpine: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/alpine.jpg",
  racingbulls: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/racing-bulls.jpg",
  haas: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/haas.jpg",
  audi: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/audi.jpg",
  cadillac: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/teams/2025/cadillac.jpg",
};

export interface Circuit {
  id: string;
  name: string;
  location: string;
  country: string;
  flag: string;
  laps: number;
  length: number;
  lapRecord: string;
  lapRecordHolder: string;
  lapRecordYear: number;
  firstGP: number;
  corners: number;
  drsZones: number;
  description: string;
  type: "street" | "permanent" | "hybrid";
  trackPath: string;
  imageUrl?: string;
}

export interface Race {
  id: string;
  round: number;
  name: string;
  circuitId: string;
  country: string;
  flag: string;
  date: string;
  status: "completed" | "upcoming" | "live";
  winner?: string;
  winnerTime?: string;
  fastestLap?: string;
  fastestLapHolder?: string;
  results?: RaceResult[];
  qualifyingResults?: QualifyingResult[];
}

export interface RaceResult {
  position: number;
  driverId: string;
  time?: string;
  gap?: string;
  points: number;
  laps: number;
  status: string;
  fastestLap?: boolean;
}

export interface QualifyingResult {
  position: number;
  driverId: string;
  q1?: string;
  q2?: string;
  q3?: string;
}

export interface NewsItem {
  id: string;
  title: string;
  summary: string;
  category: "Race" | "Team" | "Driver" | "Technical" | "Breaking";
  timeAgo: string;
  colors: string[];
}

export interface LiveDriverData {
  driverId: string;
  position: number;
  gap: string;
  interval: string;
  lap: number;
  tyreCompound: "S" | "M" | "H" | "I" | "W";
  tyreLaps: number;
  lastLapTime: string;
  sector1: string;
  sector2: string;
  sector3: string;
  pitStops: number;
  drs: boolean;
  status: "racing" | "pit" | "out" | "sc";
  trackPosition: number;
}

export const TEAMS: Team[] = [
  {
    id: "mclaren",
    name: "McLaren F1 Team",
    shortName: "McLaren",
    color: "#FF8000",
    secondColor: "#000000",
    drivers: ["norris", "piastri"],
    points: 87,
    position: 1,
    wins: 2,
    podiums: 6,
    poles: 2,
    championships: 8,
    base: "Woking, UK",
    powerUnit: "Mercedes",
    firstEntry: 1966,
    bio: "The defending constructors champions enter 2026 as the team to beat. Norris and Piastri form the most formidable driver pairing in the paddock as McLaren looks to secure an unprecedented back-to-back title.",
  },
  {
    id: "ferrari",
    name: "Scuderia Ferrari",
    shortName: "Ferrari",
    color: "#E8002D",
    secondColor: "#FFF200",
    drivers: ["leclerc", "hamilton"],
    points: 72,
    position: 2,
    wins: 1,
    podiums: 5,
    poles: 1,
    championships: 16,
    base: "Maranello, Italy",
    powerUnit: "Ferrari",
    firstEntry: 1950,
    bio: "The Scuderia enters 2026 with a renewed sense of optimism. The pairing of Leclerc and Hamilton — two of the all-time greats — gives Ferrari their most potent driver lineup in a generation.",
  },
  {
    id: "mercedes",
    name: "Mercedes-AMG Petronas",
    shortName: "Mercedes",
    color: "#27F4D2",
    secondColor: "#000000",
    drivers: ["russell", "antonelli"],
    points: 63,
    position: 3,
    wins: 1,
    podiums: 4,
    poles: 2,
    championships: 8,
    base: "Brackley, UK",
    powerUnit: "Mercedes",
    firstEntry: 2010,
    bio: "The Silver Arrows returned to form in 2026 pre-season testing, with both Russell and teenage sensation Antonelli showing blistering pace. Mercedes are confident this could be their year.",
  },
  {
    id: "redbull",
    name: "Oracle Red Bull Racing",
    shortName: "Red Bull",
    color: "#3671C6",
    secondColor: "#CC1E4A",
    drivers: ["max_verstappen", "hadjar"],
    points: 58,
    position: 4,
    wins: 1,
    podiums: 3,
    poles: 1,
    championships: 6,
    base: "Milton Keynes, UK",
    powerUnit: "Honda RBPT / Ford",
    firstEntry: 2005,
    bio: "Four-time champion Verstappen continues his Red Bull odyssey in 2026 alongside promoted junior Isack Hadjar. The new power unit regulations could either strengthen or challenge their dominance.",
  },
  {
    id: "astonmartin",
    name: "Aston Martin Aramco",
    shortName: "Aston Martin",
    color: "#229971",
    secondColor: "#00594F",
    drivers: ["alonso", "stroll"],
    points: 28,
    position: 5,
    wins: 0,
    podiums: 1,
    poles: 0,
    championships: 0,
    base: "Silverstone, UK",
    powerUnit: "Mercedes",
    firstEntry: 2021,
    bio: "The Silverstone-based squad returns with Alonso still hungry for that elusive third title. The 2026 regulations could hand the team their best championship shot yet.",
  },
  {
    id: "williams",
    name: "Williams Racing",
    shortName: "Williams",
    color: "#64C4FF",
    secondColor: "#00008B",
    drivers: ["albon", "sainz"],
    points: 22,
    position: 6,
    wins: 0,
    podiums: 0,
    poles: 0,
    championships: 7,
    base: "Grove, UK",
    powerUnit: "Mercedes",
    firstEntry: 1978,
    bio: "Williams continue their resurgence with Sainz and Albon providing experience and pace. The Grove squad are aiming for consistent points and perhaps their first podium since 2017.",
  },
  {
    id: "alpine",
    name: "BWT Alpine F1 Team",
    shortName: "Alpine",
    color: "#0093CC",
    secondColor: "#FF87BC",
    drivers: ["gasly", "colapinto"],
    points: 16,
    position: 7,
    wins: 0,
    podiums: 0,
    poles: 0,
    championships: 0,
    base: "Enstone, UK",
    powerUnit: "Renault",
    firstEntry: 2021,
    bio: "Alpine look to build on their mid-field competitiveness with Gasly and Colapinto forming an exciting pairing. The French team are targeting regular points finishes.",
  },
  {
    id: "racingbulls",
    name: "Visa Cash App Racing Bulls",
    shortName: "Racing Bulls",
    color: "#6692FF",
    secondColor: "#1434CB",
    drivers: ["lawson", "arvid_lindblad"],
    points: 12,
    position: 8,
    wins: 0,
    podiums: 0,
    poles: 0,
    championships: 0,
    base: "Faenza, Italy",
    powerUnit: "Honda RBPT / Ford",
    firstEntry: 2006,
    bio: "Red Bull's junior outfit features veteran Lawson alongside remarkable 18-year-old rookie Arvid Lindblad, who became the youngest F1 driver since Max Verstappen.",
  },
  {
    id: "haas",
    name: "MoneyGram Haas F1 Team",
    shortName: "Haas",
    color: "#B6BABD",
    secondColor: "#E8002D",
    drivers: ["ocon", "bearman"],
    points: 10,
    position: 9,
    wins: 0,
    podiums: 0,
    poles: 0,
    championships: 0,
    base: "Kannapolis, USA",
    powerUnit: "Ferrari",
    firstEntry: 2016,
    bio: "The American team continues to develop with Ocon and Bearman, targeting Q3 appearances and points finishes as they look to climb the constructor standings.",
  },
  {
    id: "audi",
    name: "Audi F1 Team",
    shortName: "Audi",
    color: "#C0002C",
    secondColor: "#000000",
    drivers: ["hulkenberg", "bortoleto"],
    points: 4,
    position: 10,
    wins: 0,
    podiums: 0,
    poles: 0,
    championships: 0,
    base: "Hinwil, Switzerland",
    powerUnit: "Audi",
    firstEntry: 2026,
    bio: "The four-ring brand makes its historic Formula 1 debut with the new 2026 power unit regulations. Hulkenberg and Bortoleto lead the charge as Audi begins a new chapter in motorsport's pinnacle series.",
  },
  {
    id: "cadillac",
    name: "Cadillac F1 Team",
    shortName: "Cadillac",
    color: "#4B5563",
    secondColor: "#9CA3AF",
    drivers: ["bottas", "perez"],
    points: 2,
    position: 11,
    wins: 0,
    podiums: 0,
    poles: 0,
    championships: 0,
    base: "Indianapolis, USA",
    powerUnit: "Ferrari",
    firstEntry: 2026,
    bio: "The iconic American Cadillac brand makes a triumphant return to Formula 1 after decades away. Bottas and Perez — two experienced campaigners — lead the new American challenger onto the grid.",
  },
];

export const DRIVERS: Driver[] = [
  {
    id: "norris",
    number: 4,
    name: "Lando Norris",
    firstName: "Lando",
    lastName: "Norris",
    shortName: "NOR",
    teamId: "mclaren",
    nationality: "British",
    flag: "🇬🇧",
    age: 26,
    podiums: 38,
    wins: 9,
    poles: 10,
    championships: 1,
    points: 47,
    position: 1,
    fastestLaps: 10,
    grandsPrix: 139,
    bio: "The 2025 World Champion enters 2026 carrying the weight of defending his title. Norris is now at his peak — combining raw speed, tactical intelligence and the confidence of a champion.",
    seasonPoints: [25, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "leclerc",
    number: 16,
    name: "Charles Leclerc",
    firstName: "Charles",
    lastName: "Leclerc",
    shortName: "LEC",
    teamId: "ferrari",
    nationality: "Monégasque",
    flag: "🇲🇨",
    age: 28,
    podiums: 46,
    wins: 9,
    poles: 26,
    championships: 0,
    points: 42,
    position: 2,
    fastestLaps: 9,
    grandsPrix: 153,
    bio: "The Monaco-born Ferrari talisman who carries the hopes of the Tifosi. In 2026, Leclerc has a car capable of winning. Will this finally be his year to conquer the championship?",
    seasonPoints: [18, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "max_verstappen",
    number: 3,
    name: "Max Verstappen",
    firstName: "Max",
    lastName: "Verstappen",
    shortName: "VER",
    teamId: "redbull",
    nationality: "Dutch",
    flag: "🇳🇱",
    age: 28,
    podiums: 116,
    wins: 64,
    poles: 43,
    championships: 4,
    points: 36,
    position: 3,
    fastestLaps: 34,
    grandsPrix: 223,
    bio: "The four-time World Champion from the Netherlands. Verstappen's combination of raw speed, racecraft, and mental strength make him one of the greatest Formula 1 drivers of all time.",
    seasonPoints: [25, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "piastri",
    number: 81,
    name: "Oscar Piastri",
    firstName: "Oscar",
    lastName: "Piastri",
    shortName: "PIA",
    teamId: "mclaren",
    nationality: "Australian",
    flag: "🇦🇺",
    age: 25,
    podiums: 28,
    wins: 6,
    poles: 4,
    championships: 0,
    points: 40,
    position: 4,
    fastestLaps: 4,
    grandsPrix: 61,
    bio: "The Australian prodigy continues to grow into one of Formula 1's most complete drivers. Piastri's composure under pressure and natural pace make him a genuine championship threat.",
    seasonPoints: [15, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "russell",
    number: 63,
    name: "George Russell",
    firstName: "George",
    lastName: "Russell",
    shortName: "RUS",
    teamId: "mercedes",
    nationality: "British",
    flag: "🇬🇧",
    age: 28,
    podiums: 24,
    wins: 4,
    poles: 5,
    championships: 0,
    points: 35,
    position: 5,
    fastestLaps: 7,
    grandsPrix: 113,
    bio: "Russell leads Mercedes' 2026 charge with his trademark analytical precision. The analytical Briton is determined that 2026 will be the year he finally challenges for the world title.",
    seasonPoints: [12, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "hamilton",
    number: 44,
    name: "Lewis Hamilton",
    firstName: "Lewis",
    lastName: "Hamilton",
    shortName: "HAM",
    teamId: "ferrari",
    nationality: "British",
    flag: "🇬🇧",
    age: 41,
    podiums: 202,
    wins: 104,
    poles: 104,
    championships: 7,
    points: 30,
    position: 6,
    fastestLaps: 68,
    grandsPrix: 360,
    bio: "The most decorated Formula 1 driver in history continues his legendary career at Ferrari. Hamilton is motivated by the chance to win an eighth championship with the iconic Italian team.",
    seasonPoints: [18, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "antonelli",
    number: 12,
    name: "Kimi Antonelli",
    firstName: "Kimi",
    lastName: "Antonelli",
    shortName: "ANT",
    teamId: "mercedes",
    nationality: "Italian",
    flag: "🇮🇹",
    age: 19,
    podiums: 4,
    wins: 1,
    poles: 2,
    championships: 0,
    points: 28,
    position: 7,
    fastestLaps: 2,
    grandsPrix: 31,
    bio: "The teenage Italian sensation who topped Bahrain pre-season testing. Antonelli is the most hyped young talent to enter Formula 1 since Verstappen — and he's already delivering on that promise.",
    seasonPoints: [10, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "alonso",
    number: 14,
    name: "Fernando Alonso",
    firstName: "Fernando",
    lastName: "Alonso",
    shortName: "ALO",
    teamId: "astonmartin",
    nationality: "Spanish",
    flag: "🇪🇸",
    age: 44,
    podiums: 108,
    wins: 32,
    poles: 22,
    championships: 2,
    points: 18,
    position: 8,
    fastestLaps: 23,
    grandsPrix: 413,
    bio: "The indestructible Spaniard who refuses to slow down. Now 44 and still battling at the front, Alonso remains one of the most remarkable stories in all of sport.",
    seasonPoints: [8, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "sainz",
    number: 55,
    name: "Carlos Sainz",
    firstName: "Carlos",
    lastName: "Sainz",
    shortName: "SAI",
    teamId: "williams",
    nationality: "Spanish",
    flag: "🇪🇸",
    age: 31,
    podiums: 24,
    wins: 3,
    poles: 6,
    championships: 0,
    points: 14,
    position: 9,
    fastestLaps: 5,
    grandsPrix: 207,
    bio: "The smooth Spaniard known for exceptional tyre management and racecraft. Sainz continues to extract maximum performance from whatever car he's given — now elevating Williams to new heights.",
    seasonPoints: [6, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "hadjar",
    number: 6,
    name: "Isack Hadjar",
    firstName: "Isack",
    lastName: "Hadjar",
    shortName: "HAD",
    teamId: "redbull",
    nationality: "French",
    flag: "🇫🇷",
    age: 21,
    podiums: 1,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 22,
    position: 10,
    fastestLaps: 0,
    grandsPrix: 31,
    bio: "Promoted to the senior Red Bull seat for 2026, Hadjar faces the ultimate challenge — partnering four-time champion Verstappen. His car control and racecraft under pressure have already impressed.",
    seasonPoints: [12, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "gasly",
    number: 10,
    name: "Pierre Gasly",
    firstName: "Pierre",
    lastName: "Gasly",
    shortName: "GAS",
    teamId: "alpine",
    nationality: "French",
    flag: "🇫🇷",
    age: 30,
    podiums: 4,
    wins: 1,
    poles: 0,
    championships: 0,
    points: 10,
    position: 11,
    fastestLaps: 3,
    grandsPrix: 162,
    bio: "The electric Frenchman leads Alpine's 2026 project with the experience and determination of a driver who knows the paddock inside out.",
    seasonPoints: [4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "albon",
    number: 23,
    name: "Alex Albon",
    firstName: "Alex",
    lastName: "Albon",
    shortName: "ALB",
    teamId: "williams",
    nationality: "Thai",
    flag: "🇹🇭",
    age: 29,
    podiums: 2,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 8,
    position: 12,
    fastestLaps: 1,
    grandsPrix: 94,
    bio: "The Thai-British driver continues to punch above his weight at Williams. Albon's sublime car control and tyre preservation are assets any team would desire.",
    seasonPoints: [2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "stroll",
    number: 18,
    name: "Lance Stroll",
    firstName: "Lance",
    lastName: "Stroll",
    shortName: "STR",
    teamId: "astonmartin",
    nationality: "Canadian",
    flag: "🇨🇦",
    age: 27,
    podiums: 3,
    wins: 0,
    poles: 1,
    championships: 0,
    points: 10,
    position: 13,
    fastestLaps: 0,
    grandsPrix: 166,
    bio: "Lance Stroll continues to grow as a Formula 1 driver, with his wet-weather expertise and racecraft making him a dangerous proposition in the right conditions.",
    seasonPoints: [4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "ocon",
    number: 31,
    name: "Esteban Ocon",
    firstName: "Esteban",
    lastName: "Ocon",
    shortName: "OCO",
    teamId: "haas",
    nationality: "French",
    flag: "🇫🇷",
    age: 29,
    podiums: 3,
    wins: 1,
    poles: 0,
    championships: 0,
    points: 6,
    position: 14,
    fastestLaps: 0,
    grandsPrix: 157,
    bio: "The gritty Frenchman brings race-winning pedigree and hard-won experience to Haas, determined to prove he belongs at the front of the pack.",
    seasonPoints: [2, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "lawson",
    number: 30,
    name: "Liam Lawson",
    firstName: "Liam",
    lastName: "Lawson",
    shortName: "LAW",
    teamId: "racingbulls",
    nationality: "New Zealander",
    flag: "🇳🇿",
    age: 23,
    podiums: 0,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 8,
    position: 15,
    fastestLaps: 0,
    grandsPrix: 31,
    bio: "Having proven himself in the Red Bull system, Lawson now leads Racing Bulls with experience and confidence, ready to take the step to the senior team.",
    seasonPoints: [4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "bearman",
    number: 87,
    name: "Oliver Bearman",
    firstName: "Oliver",
    lastName: "Bearman",
    shortName: "BEA",
    teamId: "haas",
    nationality: "British",
    flag: "🇬🇧",
    age: 20,
    podiums: 0,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 4,
    position: 16,
    fastestLaps: 0,
    grandsPrix: 31,
    bio: "The young British talent continues to develop at Haas. Bearman's potential is undoubted, and 2026 could be the year he announces himself as a future top-team driver.",
    seasonPoints: [0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "colapinto",
    number: 43,
    name: "Franco Colapinto",
    firstName: "Franco",
    lastName: "Colapinto",
    shortName: "COL",
    teamId: "alpine",
    nationality: "Argentine",
    flag: "🇦🇷",
    age: 22,
    podiums: 0,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 0,
    position: 17,
    fastestLaps: 0,
    grandsPrix: 12,
    bio: "The Argentine sensation who made a remarkable impression at Williams in 2024. Colapinto earned his full-time 2026 seat at Alpine through raw speed and fearless racecraft.",
    seasonPoints: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "hulkenberg",
    number: 27,
    name: "Nico Hülkenberg",
    firstName: "Nico",
    lastName: "Hülkenberg",
    shortName: "HUL",
    teamId: "audi",
    nationality: "German",
    flag: "🇩🇪",
    age: 38,
    podiums: 0,
    wins: 0,
    poles: 1,
    championships: 0,
    points: 4,
    position: 18,
    fastestLaps: 2,
    grandsPrix: 232,
    bio: "Leading Audi's historic F1 debut, Hulkenberg brings his vast experience and race craft to the challenge of developing a brand new power unit from scratch. A landmark role for the popular German.",
    seasonPoints: [2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "bortoleto",
    number: 5,
    name: "Gabriel Bortoleto",
    firstName: "Gabriel",
    lastName: "Bortoleto",
    shortName: "BOR",
    teamId: "audi",
    nationality: "Brazilian",
    flag: "🇧🇷",
    age: 21,
    podiums: 0,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 0,
    position: 19,
    fastestLaps: 0,
    grandsPrix: 31,
    bio: "The young Brazilian is one of the most exciting talents in the paddock. Partnered with Hulkenberg at the new Audi team, Bortoleto's job is to extract the most from the new German machine.",
    seasonPoints: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "arvid_lindblad",
    number: 41,
    name: "Arvid Lindblad",
    firstName: "Arvid",
    lastName: "Lindblad",
    shortName: "LIN",
    teamId: "racingbulls",
    nationality: "British",
    flag: "🇬🇧",
    age: 18,
    podiums: 0,
    wins: 0,
    poles: 0,
    championships: 0,
    points: 4,
    position: 20,
    fastestLaps: 0,
    grandsPrix: 2,
    bio: "The youngest driver on the 2026 grid, Lindblad became the youngest F1 driver since Max Verstappen at just 18 years old. The Red Bull-backed British youngster is already turning heads.",
    seasonPoints: [2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "bottas",
    number: 77,
    name: "Valtteri Bottas",
    firstName: "Valtteri",
    lastName: "Bottas",
    shortName: "BOT",
    teamId: "cadillac",
    nationality: "Finnish",
    flag: "🇫🇮",
    age: 36,
    podiums: 67,
    wins: 10,
    poles: 20,
    championships: 0,
    points: 2,
    position: 21,
    fastestLaps: 19,
    grandsPrix: 243,
    bio: "Bottas makes a remarkable return to F1 with the new American Cadillac team. The popular Finn brings ten race wins and immense experience to help build a brand new team from the ground up.",
    seasonPoints: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
  {
    id: "perez",
    number: 11,
    name: "Sergio Perez",
    firstName: "Sergio",
    lastName: "Perez",
    shortName: "PER",
    teamId: "cadillac",
    nationality: "Mexican",
    flag: "🇲🇽",
    age: 36,
    podiums: 45,
    wins: 6,
    poles: 3,
    championships: 0,
    points: 0,
    position: 22,
    fastestLaps: 10,
    grandsPrix: 291,
    bio: "Sergio Perez returns to F1 alongside Bottas at Cadillac after being dropped by Red Bull at the end of 2024. The crowd favourite from Mexico is hungry to prove he belongs back in the sport.",
    seasonPoints: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    photo: null,
  },
];

export const CIRCUITS: Circuit[] = [
  {
    id: "australia",
    name: "Albert Park Circuit",
    location: "Melbourne",
    country: "Australia",
    flag: "🇦🇺",
    laps: 58,
    length: 5.278,
    lapRecord: "1:19.813",
    lapRecordHolder: "Charles Leclerc",
    lapRecordYear: 2022,
    firstGP: 1996,
    corners: 16,
    drsZones: 4,
    description: "Set around the picturesque Albert Park Lake, Melbourne's street circuit offers a spectacular setting for the season opener. The circuit's recent modifications have created even faster and more exciting racing.",
    type: "street",
    trackPath: "M 50 80 C 80 80 100 70 110 50 C 120 30 115 10 100 5 C 85 0 60 10 50 25 C 40 40 30 50 25 60 C 20 70 30 80 50 80 Z",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Australia_Circuit.png",
  },
  {
    id: "jeddah",
    name: "Jeddah Corniche Circuit",
    location: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    laps: 50,
    length: 6.174,
    lapRecord: "1:30.734",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2021,
    firstGP: 2021,
    corners: 27,
    drsZones: 3,
    description: "The fastest street circuit in Formula 1, Jeddah's narrow walls and ultra-high speeds create an intense, nerve-shredding spectacle along the Red Sea waterfront.",
    type: "street",
    trackPath: "M 20 90 L 20 20 C 20 10 30 5 40 8 L 80 8 C 90 8 95 12 95 20 L 95 35 C 95 42 90 45 85 45 L 60 45 C 55 45 52 48 52 53 L 52 65 C 52 70 55 73 60 73 L 85 73 C 90 73 95 76 95 82 L 95 88 C 95 94 90 98 85 98 L 25 98 C 20 98 15 94 15 88 L 20 90",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Saudi_Arabia_Circuit.png",
  },
  {
    id: "bahrain",
    name: "Bahrain International Circuit",
    location: "Sakhir",
    country: "Bahrain",
    flag: "🇧🇭",
    laps: 57,
    length: 5.412,
    lapRecord: "1:31.447",
    lapRecordHolder: "Pedro de la Rosa",
    lapRecordYear: 2005,
    firstGP: 2004,
    corners: 15,
    drsZones: 3,
    description: "The desert circuit at Sakhir hosts the Formula 1 calendar. Its mix of slow corners and long straights rewards both technical and power-hungry machinery.",
    type: "permanent",
    trackPath: "M 30 85 C 15 75 10 60 15 45 C 20 30 35 20 55 18 C 70 16 85 22 90 35 C 95 48 88 62 80 68 L 65 72 C 60 74 55 70 55 65 L 55 55 C 55 48 50 43 45 45 L 35 48 C 28 52 25 60 28 68 L 30 85",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Bahrain_Circuit.png",
  },
  {
    id: "china",
    name: "Shanghai International Circuit",
    location: "Shanghai",
    country: "China",
    flag: "🇨🇳",
    laps: 56,
    length: 5.451,
    lapRecord: "1:32.238",
    lapRecordHolder: "Michael Schumacher",
    lapRecordYear: 2004,
    firstGP: 2004,
    corners: 16,
    drsZones: 2,
    description: "Shanghai's technical circuit features long, sweeping corners and a distinctive snail-shaped final sector. The extended back straight creates multiple overtaking opportunities.",
    type: "permanent",
    trackPath: "M 15 50 C 15 30 25 15 45 10 C 65 5 80 15 85 30 L 85 45 C 85 52 80 57 73 57 C 60 57 50 50 40 55 C 30 60 25 72 30 82 L 45 90 C 55 95 65 92 72 85 C 80 78 78 68 70 65 C 62 62 55 65 52 72 C 49 79 52 86 58 88 L 70 90 C 80 92 90 85 92 75 L 88 55",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/China_Circuit.png",
  },
  {
    id: "miami",
    name: "Miami International Autodrome",
    location: "Miami Gardens",
    country: "USA",
    flag: "🇺🇸",
    laps: 57,
    length: 5.412,
    lapRecord: "1:29.708",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2023,
    firstGP: 2022,
    corners: 19,
    drsZones: 3,
    description: "The flashy street circuit around the Hard Rock Stadium offers Formula 1's most glamorous backdrop. Miami's mix of long straights and technical sections creates varied racing.",
    type: "street",
    trackPath: "M 10 70 L 10 30 C 10 18 18 10 30 10 L 80 10 C 90 10 95 16 95 26 L 95 40 C 95 50 88 56 78 56 L 55 56 C 45 56 38 62 38 72 L 38 80 C 38 88 43 93 53 93 L 88 93 C 93 93 97 89 97 84 L 97 72",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Miami_Circuit.png",
  },
  {
    id: "monaco",
    name: "Circuit de Monaco",
    location: "Monte Carlo",
    country: "Monaco",
    flag: "🇲🇨",
    laps: 78,
    length: 3.337,
    lapRecord: "1:12.909",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2021,
    firstGP: 1950,
    corners: 19,
    drsZones: 1,
    description: "The jewel of Formula 1, Monaco's narrow streets through Monte Carlo represent the ultimate test of concentration and precision.",
    type: "street",
    trackPath: "M 20 90 L 20 50 C 20 35 28 25 42 20 L 55 15 C 65 12 72 15 75 22 L 78 35 C 80 42 76 48 70 50 L 60 52 C 52 54 48 60 50 68 L 55 78 C 58 85 65 90 73 88 L 82 82 C 88 78 90 70 87 62",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Monaco_Circuit.png",
  },
  {
    id: "canada",
    name: "Circuit Gilles Villeneuve",
    location: "Montreal",
    country: "Canada",
    flag: "🇨🇦",
    laps: 70,
    length: 4.361,
    lapRecord: "1:13.078",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2019,
    firstGP: 1978,
    corners: 14,
    drsZones: 2,
    description: "The power circuit on the Île Notre-Dame is beloved by drivers and fans alike. Hard braking zones, walls of champions and chicanes create drama at every grand prix.",
    type: "street",
    trackPath: "M 50 95 L 10 95 L 10 30 C 10 18 18 10 30 10 L 70 10 C 82 10 90 18 90 30 L 90 60 C 90 68 85 73 78 73 L 65 73 C 58 73 52 78 52 85 L 52 95",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Canada_Circuit.png",
  },
  {
    id: "silverstone",
    name: "Silverstone Circuit",
    location: "Northamptonshire",
    country: "Great Britain",
    flag: "🇬🇧",
    laps: 52,
    length: 5.891,
    lapRecord: "1:27.097",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2020,
    firstGP: 1950,
    corners: 18,
    drsZones: 2,
    description: "The home of British motorsport and host of the very first Formula 1 World Championship race. Silverstone's high-speed corners are the ultimate test of driver commitment.",
    type: "permanent",
    trackPath: "M 20 55 C 15 45 15 32 22 24 L 38 12 C 48 6 60 8 68 16 L 82 32 C 88 40 87 52 80 58 L 72 65 C 78 72 78 82 72 88 L 58 92 C 48 95 38 92 32 85 L 20 72 C 18 65 18 58 20 55",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Great_Britain_Circuit.png",
  },
  {
    id: "hungary",
    name: "Hungaroring",
    location: "Budapest",
    country: "Hungary",
    flag: "🇭🇺",
    laps: 70,
    length: 4.381,
    lapRecord: "1:16.627",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2020,
    firstGP: 1986,
    corners: 14,
    drsZones: 1,
    description: "Often described as 'Monaco without the walls', the Hungaroring's tight, twisty layout makes overtaking extremely difficult and places a premium on qualifying pace.",
    type: "permanent",
    trackPath: "M 20 50 C 18 35 25 20 40 15 L 60 12 C 72 10 80 18 80 30 L 78 42 C 76 50 70 55 62 55 L 50 55 C 42 55 36 60 36 68 L 36 80 C 36 88 42 93 50 93 L 68 93 C 76 93 82 87 82 80 L 82 68",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Hungary_Circuit.png",
  },
  {
    id: "spa",
    name: "Circuit de Spa-Francorchamps",
    location: "Spa",
    country: "Belgium",
    flag: "🇧🇪",
    laps: 44,
    length: 7.004,
    lapRecord: "1:46.286",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2018,
    firstGP: 1950,
    corners: 19,
    drsZones: 2,
    description: "The legendary Belgian circuit in the Ardennes forest is many drivers' favourite race venue. Spa's Eau Rouge, Pouhon and Blanchimont are among the most breathtaking corners in motorsport.",
    type: "permanent",
    trackPath: "M 50 90 L 15 60 C 8 52 8 40 15 33 L 30 22 C 38 16 48 16 55 22 L 62 30 C 68 36 68 46 62 52 L 55 58 C 60 65 68 70 75 65 L 85 55 C 90 48 90 38 85 32 L 75 22 C 70 16 78 8 85 12 L 90 18",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Belgium_Circuit.png",
  },
  {
    id: "monza",
    name: "Autodromo Nazionale Monza",
    location: "Monza",
    country: "Italy",
    flag: "🇮🇹",
    laps: 51,
    length: 5.793,
    lapRecord: "1:21.046",
    lapRecordHolder: "Rubens Barrichello",
    lapRecordYear: 2004,
    firstGP: 1950,
    corners: 11,
    drsZones: 2,
    description: "The Temple of Speed. Monza's ultra-high-speed layout produces the highest top speeds in Formula 1. A unique, historic venue beloved by the passionate Tifosi.",
    type: "permanent",
    trackPath: "M 20 80 L 20 30 C 20 18 28 10 40 10 L 80 10 C 88 10 92 16 90 24 L 85 35 C 82 42 75 45 68 42 L 55 35 C 48 32 45 25 48 18 M 60 45 L 60 80 C 60 88 68 95 78 95 L 85 95",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Italy_Circuit.png",
  },
  {
    id: "singapore",
    name: "Marina Bay Street Circuit",
    location: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    laps: 61,
    length: 5.063,
    lapRecord: "1:35.867",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2023,
    firstGP: 2008,
    corners: 23,
    drsZones: 3,
    description: "The only Formula 1 race held entirely under artificial lights, Singapore's Marina Bay circuit is one of the most physically and mentally demanding on the calendar.",
    type: "street",
    trackPath: "M 15 85 L 15 40 C 15 28 22 20 34 18 L 50 15 C 58 13 65 16 68 22 L 72 32 C 75 38 73 45 68 50 L 60 55 C 52 60 48 68 50 76 L 55 84 C 58 90 65 95 73 93 L 82 88 C 88 84 90 78 87 72 L 80 62 C 76 55 78 45 85 42 L 92 38",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Singapore_Circuit.png",
  },
  {
    id: "austin",
    name: "Circuit of The Americas",
    location: "Austin",
    country: "USA",
    flag: "🇺🇸",
    laps: 56,
    length: 5.513,
    lapRecord: "1:36.169",
    lapRecordHolder: "Charles Leclerc",
    lapRecordYear: 2019,
    firstGP: 2012,
    corners: 20,
    drsZones: 2,
    description: "America's first purpose-built Formula 1 circuit combines iconic corners from legendary tracks worldwide. COTA's stadium section, esses and Turn 1 elevation change create a spectacular venue.",
    type: "permanent",
    trackPath: "M 50 90 L 15 90 L 15 45 C 15 30 22 18 36 14 L 55 10 C 70 8 80 18 80 32 L 78 48 C 76 56 70 62 62 62 L 50 62 C 42 62 36 68 38 76 L 42 85 C 45 90 50 93 55 90",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/USA_Circuit.png",
  },
  {
    id: "mexico",
    name: "Autodromo Hermanos Rodriguez",
    location: "Mexico City",
    country: "Mexico",
    flag: "🇲🇽",
    laps: 71,
    length: 4.304,
    lapRecord: "1:17.774",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2021,
    firstGP: 1963,
    corners: 17,
    drsZones: 3,
    description: "At 2,285 metres above sea level, Mexico City's thin air creates unique engineering challenges. The famous stadium section through the baseball outfield creates an incredible atmosphere.",
    type: "permanent",
    trackPath: "M 15 55 C 12 40 18 25 32 18 L 55 12 C 70 8 82 18 82 32 L 80 48 C 78 56 72 62 64 62 L 50 62 C 42 62 36 68 38 76 L 48 84 C 54 90 62 90 68 84 L 76 72 C 80 65 78 55 72 50 L 65 46 C 58 42 55 35 58 28",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Mexico_Circuit.png",
  },
  {
    id: "brazil",
    name: "Autodromo Jose Carlos Pace",
    location: "São Paulo",
    country: "Brazil",
    flag: "🇧🇷",
    laps: 71,
    length: 4.309,
    lapRecord: "1:10.540",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2018,
    firstGP: 1973,
    corners: 15,
    drsZones: 2,
    description: "Interlagos is Formula 1's emotional heart, where history is made with stunning regularity. The anti-clockwise circuit at altitude, combined with unpredictable weather, produces dramatic races.",
    type: "permanent",
    trackPath: "M 50 90 L 20 90 L 15 55 C 12 40 18 25 32 18 L 60 12 C 75 8 88 20 88 35 L 85 55 C 83 65 76 72 67 72 L 55 72 C 46 72 40 78 42 87 L 50 90",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Brazil_Circuit.png",
  },
  {
    id: "abudhabi",
    name: "Yas Marina Circuit",
    location: "Abu Dhabi",
    country: "UAE",
    flag: "🇦🇪",
    laps: 58,
    length: 5.281,
    lapRecord: "1:26.103",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2021,
    firstGP: 2009,
    corners: 16,
    drsZones: 2,
    description: "The stunning Yas Marina Circuit provides the perfect curtain-closer to the Formula 1 season. Its marina setting and floodlit grandeur make it one of the most talked-about circuits on the calendar.",
    type: "street",
    trackPath: "M 20 75 L 20 35 C 20 22 28 14 40 12 L 70 12 C 82 12 88 20 88 32 L 88 50 C 88 60 82 65 73 65 L 58 65 C 50 65 45 70 45 78 L 45 85 C 45 90 50 94 56 94 L 80 94 C 87 94 92 89 92 83",
    imageUrl: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/Abu_Dhabi_Circuit.png",
  },
];

export const RACES_2026: Race[] = [
  {
    id: "australia-2026",
    round: 1,
    name: "Australian Grand Prix",
    circuitId: "australia",
    country: "Australia",
    flag: "🇦🇺",
    date: "2026-03-08",
    status: "completed",
    winner: "norris",
    winnerTime: "1:29:44.381",
    fastestLap: "1:19.931",
    fastestLapHolder: "piastri",
    results: [
      { position: 1, driverId: "norris", time: "1:29:44.381", gap: "Winner", points: 25, laps: 58, status: "Finished" },
      { position: 2, driverId: "piastri", time: "1:29:51.214", gap: "+6.833s", points: 18, laps: 58, status: "Finished" },
      { position: 3, driverId: "leclerc", time: "1:29:58.442", gap: "+14.061s", points: 15, laps: 58, status: "Finished" },
      { position: 4, driverId: "hamilton", time: "1:30:05.991", gap: "+21.610s", points: 12, laps: 58, status: "Finished" },
      { position: 5, driverId: "russell", time: "1:30:12.441", gap: "+28.060s", points: 10, laps: 58, status: "Finished" },
      { position: 6, driverId: "sainz", time: "1:30:22.111", gap: "+37.730s", points: 8, laps: 58, status: "Finished" },
      { position: 7, driverId: "max_verstappen", time: "1:30:28.334", gap: "+43.953s", points: 6, laps: 58, status: "Finished" },
      { position: 8, driverId: "alonso", time: "1:30:38.112", gap: "+53.731s", points: 4, laps: 58, status: "Finished" },
      { position: 9, driverId: "antonelli", time: "1:30:45.441", gap: "+1:01.060s", points: 2, laps: 58, status: "Finished" },
      { position: 10, driverId: "hadjar", time: "1:30:51.001", gap: "+1:06.620s", points: 1, laps: 58, status: "Finished" },
    ],
    qualifyingResults: [
      { position: 1, driverId: "norris", q1: "1:17.112", q2: "1:16.888", q3: "1:16.442" },
      { position: 2, driverId: "leclerc", q1: "1:17.334", q2: "1:17.001", q3: "1:16.551" },
      { position: 3, driverId: "piastri", q1: "1:17.445", q2: "1:17.112", q3: "1:16.778" },
      { position: 4, driverId: "russell", q1: "1:17.556", q2: "1:17.223", q3: "1:16.889" },
      { position: 5, driverId: "hamilton", q1: "1:17.667", q2: "1:17.334", q3: "1:17.001" },
    ],
  },
  {
    id: "jeddah-2026",
    round: 2,
    name: "Saudi Arabian Grand Prix",
    circuitId: "jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    date: "2026-03-22",
    status: "upcoming",
    qualifyingResults: [
      { position: 1, driverId: "leclerc", q1: "1:26.445", q2: "1:26.112", q3: "1:25.889" },
      { position: 2, driverId: "max_verstappen", q1: "1:26.667", q2: "1:26.334", q3: "1:26.001" },
      { position: 3, driverId: "norris", q1: "1:26.889", q2: "1:26.556", q3: "1:26.223" },
    ],
  },
  {
    id: "bahrain-2026",
    round: 3,
    name: "Bahrain Grand Prix",
    circuitId: "bahrain",
    country: "Bahrain",
    flag: "🇧🇭",
    date: "2026-04-05",
    status: "upcoming",
  },
  {
    id: "china-2026",
    round: 4,
    name: "Chinese Grand Prix",
    circuitId: "china",
    country: "China",
    flag: "🇨🇳",
    date: "2026-04-19",
    status: "upcoming",
  },
  {
    id: "miami-2026",
    round: 5,
    name: "Miami Grand Prix",
    circuitId: "miami",
    country: "USA",
    flag: "🇺🇸",
    date: "2026-05-03",
    status: "upcoming",
  },
  {
    id: "monaco-2026",
    round: 6,
    name: "Monaco Grand Prix",
    circuitId: "monaco",
    country: "Monaco",
    flag: "🇲🇨",
    date: "2026-05-24",
    status: "upcoming",
  },
  {
    id: "canada-2026",
    round: 7,
    name: "Canadian Grand Prix",
    circuitId: "canada",
    country: "Canada",
    flag: "🇨🇦",
    date: "2026-06-14",
    status: "upcoming",
  },
  {
    id: "silverstone-2026",
    round: 8,
    name: "British Grand Prix",
    circuitId: "silverstone",
    country: "Great Britain",
    flag: "🇬🇧",
    date: "2026-07-05",
    status: "upcoming",
  },
  {
    id: "hungary-2026",
    round: 9,
    name: "Hungarian Grand Prix",
    circuitId: "hungary",
    country: "Hungary",
    flag: "🇭🇺",
    date: "2026-07-26",
    status: "upcoming",
  },
  {
    id: "spa-2026",
    round: 10,
    name: "Belgian Grand Prix",
    circuitId: "spa",
    country: "Belgium",
    flag: "🇧🇪",
    date: "2026-08-02",
    status: "upcoming",
  },
  {
    id: "monza-2026",
    round: 11,
    name: "Italian Grand Prix",
    circuitId: "monza",
    country: "Italy",
    flag: "🇮🇹",
    date: "2026-09-06",
    status: "upcoming",
  },
  {
    id: "singapore-2026",
    round: 12,
    name: "Singapore Grand Prix",
    circuitId: "singapore",
    country: "Singapore",
    flag: "🇸🇬",
    date: "2026-09-20",
    status: "upcoming",
  },
  {
    id: "austin-2026",
    round: 13,
    name: "United States Grand Prix",
    circuitId: "austin",
    country: "USA",
    flag: "🇺🇸",
    date: "2026-10-18",
    status: "upcoming",
  },
  {
    id: "mexico-2026",
    round: 14,
    name: "Mexico City Grand Prix",
    circuitId: "mexico",
    country: "Mexico",
    flag: "🇲🇽",
    date: "2026-11-01",
    status: "upcoming",
  },
  {
    id: "brazil-2026",
    round: 15,
    name: "São Paulo Grand Prix",
    circuitId: "brazil",
    country: "Brazil",
    flag: "🇧🇷",
    date: "2026-11-15",
    status: "upcoming",
  },
  {
    id: "abudhabi-2026",
    round: 24,
    name: "Abu Dhabi Grand Prix",
    circuitId: "abudhabi",
    country: "UAE",
    flag: "🇦🇪",
    date: "2026-12-06",
    status: "upcoming",
  },
];

export const NEWS: NewsItem[] = [
  {
    id: "1",
    title: "Leclerc storms to pole for Saudi Arabian GP as Ferrari dominate qualifying",
    summary: "Charles Leclerc put Ferrari back on top with a stunning pole position lap at Jeddah, half a second clear of Verstappen and Norris as the new power unit regulations favour the Italian team.",
    category: "Race",
    timeAgo: "3h ago",
    colors: ["#E8002D", "#8B0000"],
  },
  {
    id: "2",
    title: "Norris 'over the moon' after perfect Australian GP victory to open title defence",
    summary: "Lando Norris backed up his 2025 championship with a commanding season opener in Melbourne, leading from pole to flag as defending champion begins his title defence in style.",
    category: "Driver",
    timeAgo: "5d ago",
    colors: ["#FF8000", "#CC5500"],
  },
  {
    id: "3",
    title: "Cadillac and Audi — how the new teams are faring in their debut season",
    summary: "F1's two new teams are in contrasting positions after the opening round. Cadillac's Bottas scored points on debut while Audi struggled with their new power unit.",
    category: "Team",
    timeAgo: "5d ago",
    colors: ["#4B5563", "#222831"],
  },
  {
    id: "4",
    title: "Lindblad — the 18-year-old rookie already impressing veterans in F1",
    summary: "Arvid Lindblad made an immediate impression on debut at the Australian GP, finishing 15th on his first Formula 1 start and showing composure beyond his years.",
    category: "Driver",
    timeAgo: "6d ago",
    colors: ["#6692FF", "#1434CB"],
  },
  {
    id: "5",
    title: "2026 power units: Which manufacturer has the edge and why Mercedes look different",
    summary: "A deep dive into how the all-new 2026 power unit regulations are shaking up the competitive order, with Mercedes and Ferrari appearing to have made the strongest steps.",
    category: "Technical",
    timeAgo: "1w ago",
    colors: ["#27F4D2", "#005555"],
  },
  {
    id: "6",
    title: "Hamilton on 41 and still going: 'I have more desire than ever to win'",
    summary: "Seven-time world champion Lewis Hamilton opens up about his 2026 motivation, his partnership with Leclerc at Ferrari and why he believes this season could be his finest hour.",
    category: "Breaking",
    timeAgo: "1w ago",
    colors: ["#E8002D", "#330000"],
  },
];

export const LIVE_RACE_DRIVERS_INITIAL: LiveDriverData[] = [
  { driverId: "leclerc", position: 1, gap: "Leader", interval: "—", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:29.334", sector1: "28.441", sector2: "37.211", sector3: "23.682", pitStops: 0, drs: false, status: "racing", trackPosition: 0 },
  { driverId: "max_verstappen", position: 2, gap: "+1.234s", interval: "+1.234s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:29.601", sector1: "28.551", sector2: "37.301", sector3: "23.749", pitStops: 0, drs: true, status: "racing", trackPosition: 5 },
  { driverId: "norris", position: 3, gap: "+2.881s", interval: "+1.647s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:29.812", sector1: "28.661", sector2: "37.411", sector3: "23.740", pitStops: 0, drs: true, status: "racing", trackPosition: 9 },
  { driverId: "piastri", position: 4, gap: "+4.112s", interval: "+1.231s", lap: 1, tyreCompound: "S", tyreLaps: 1, lastLapTime: "1:30.001", sector1: "28.771", sector2: "37.521", sector3: "23.709", pitStops: 0, drs: true, status: "racing", trackPosition: 13 },
  { driverId: "hamilton", position: 5, gap: "+5.668s", interval: "+1.556s", lap: 1, tyreCompound: "S", tyreLaps: 1, lastLapTime: "1:30.223", sector1: "28.881", sector2: "37.631", sector3: "23.711", pitStops: 0, drs: false, status: "racing", trackPosition: 17 },
  { driverId: "russell", position: 6, gap: "+7.334s", interval: "+1.666s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:30.445", sector1: "28.991", sector2: "37.741", sector3: "23.713", pitStops: 0, drs: false, status: "racing", trackPosition: 21 },
  { driverId: "antonelli", position: 7, gap: "+9.112s", interval: "+1.778s", lap: 1, tyreCompound: "S", tyreLaps: 1, lastLapTime: "1:30.667", sector1: "29.101", sector2: "37.851", sector3: "23.715", pitStops: 0, drs: false, status: "racing", trackPosition: 25 },
  { driverId: "hadjar", position: 8, gap: "+11.001s", interval: "+1.889s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:30.889", sector1: "29.211", sector2: "37.961", sector3: "23.717", pitStops: 0, drs: false, status: "racing", trackPosition: 29 },
  { driverId: "alonso", position: 9, gap: "+13.112s", interval: "+2.111s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:31.111", sector1: "29.321", sector2: "38.071", sector3: "23.719", pitStops: 0, drs: false, status: "racing", trackPosition: 33 },
  { driverId: "sainz", position: 10, gap: "+15.334s", interval: "+2.222s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:31.334", sector1: "29.431", sector2: "38.181", sector3: "23.723", pitStops: 0, drs: false, status: "racing", trackPosition: 37 },
  { driverId: "gasly", position: 11, gap: "+18.001s", interval: "+2.667s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:31.556", sector1: "29.541", sector2: "38.291", sector3: "23.725", pitStops: 0, drs: false, status: "racing", trackPosition: 41 },
  { driverId: "albon", position: 12, gap: "+20.667s", interval: "+2.666s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:31.778", sector1: "29.651", sector2: "38.401", sector3: "23.727", pitStops: 0, drs: false, status: "racing", trackPosition: 45 },
  { driverId: "ocon", position: 13, gap: "+23.112s", interval: "+2.445s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:32.001", sector1: "29.761", sector2: "38.511", sector3: "23.730", pitStops: 0, drs: false, status: "racing", trackPosition: 49 },
  { driverId: "stroll", position: 14, gap: "+25.778s", interval: "+2.666s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:32.223", sector1: "29.871", sector2: "38.621", sector3: "23.732", pitStops: 0, drs: false, status: "racing", trackPosition: 53 },
  { driverId: "lawson", position: 15, gap: "+28.001s", interval: "+2.223s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:32.445", sector1: "29.981", sector2: "38.731", sector3: "23.734", pitStops: 0, drs: false, status: "racing", trackPosition: 57 },
  { driverId: "colapinto", position: 16, gap: "+30.778s", interval: "+2.777s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:32.667", sector1: "30.091", sector2: "38.841", sector3: "23.736", pitStops: 0, drs: false, status: "racing", trackPosition: 61 },
  { driverId: "bearman", position: 17, gap: "+33.112s", interval: "+2.334s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:32.889", sector1: "30.201", sector2: "38.951", sector3: "23.738", pitStops: 0, drs: false, status: "racing", trackPosition: 65 },
  { driverId: "hulkenberg", position: 18, gap: "+36.001s", interval: "+2.889s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:33.112", sector1: "30.311", sector2: "39.061", sector3: "23.741", pitStops: 0, drs: false, status: "racing", trackPosition: 69 },
  { driverId: "arvid_lindblad", position: 19, gap: "+38.778s", interval: "+2.777s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:33.334", sector1: "30.421", sector2: "39.171", sector3: "23.743", pitStops: 0, drs: false, status: "racing", trackPosition: 73 },
  { driverId: "bortoleto", position: 20, gap: "+41.112s", interval: "+2.334s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:33.556", sector1: "30.531", sector2: "39.281", sector3: "23.745", pitStops: 0, drs: false, status: "racing", trackPosition: 77 },
  { driverId: "bottas", position: 21, gap: "+44.001s", interval: "+2.889s", lap: 1, tyreCompound: "M", tyreLaps: 1, lastLapTime: "1:33.778", sector1: "30.641", sector2: "39.391", sector3: "23.748", pitStops: 0, drs: false, status: "racing", trackPosition: 82 },
  { driverId: "perez", position: 22, gap: "+47.112s", interval: "+3.111s", lap: 1, tyreCompound: "H", tyreLaps: 1, lastLapTime: "1:34.001", sector1: "30.751", sector2: "39.501", sector3: "23.750", pitStops: 0, drs: false, status: "racing", trackPosition: 87 },
];

export function getTeam(teamId: string): Team | undefined {
  return TEAMS.find((t) => t.id === teamId);
}

export function getDriver(driverId: string): Driver | undefined {
  return DRIVERS.find((d) => d.id === driverId);
}

export function getCircuit(circuitId: string): Circuit | undefined {
  return CIRCUITS.find((c) => c.id === circuitId);
}

export function getNextRace(): Race | undefined {
  return RACES_2026.find((r) => r.status === "upcoming");
}

export function getLiveRace(): Race | undefined {
  return RACES_2026.find((r) => r.status === "live");
}
